import { useEffect, useState } from "react";
import { App } from "./App";
import { AdminConsole } from "./Admin";
import { authApi, setCsrfToken, type User } from "./api";

type AuthState = { loading: boolean; user?: User; setupRequired?: boolean };

export function Root() {
  const [state, setState] = useState<AuthState>({ loading: true }); const [adminOpen, setAdminOpen] = useState(false); const [passwordOpen, setPasswordOpen] = useState(false);
  const load = () => { void authApi.me().then(({ user, csrfToken }) => { setCsrfToken(csrfToken); setState({ loading: false, user }); }).catch(() => { void authApi.setupStatus().then(({ required }) => setState({ loading: false, setupRequired: required })).catch(() => setState({ loading: false })); }); };
  useEffect(load, []);
  if (state.loading) return <div className="auth-shell"><div className="loading"><i /><span>Starting Sightglass…</span></div></div>;
  if (!state.user) return <AuthScreen setupRequired={Boolean(state.setupRequired)} signedIn={load} />;
  return <><App /><div className="account-bar"><span>{state.user.email}</span><button onClick={() => setPasswordOpen(true)}>Password</button>{state.user.role === "admin" ? <button onClick={() => setAdminOpen(true)}>Settings</button> : null}<button onClick={() => { void authApi.logout().finally(() => window.location.reload()); }}>Sign out</button></div>{state.user.mustChangePassword || passwordOpen ? <PasswordChange close={() => { setPasswordOpen(false); load(); }} required={state.user.mustChangePassword} /> : null}{adminOpen ? <AdminConsole currentUser={state.user} close={() => setAdminOpen(false)} /> : null}</>;
}

function AuthScreen({ setupRequired, signedIn }: { setupRequired: boolean; signedIn(): void }) {
  const query = new URLSearchParams(window.location.search); const setup = query.get("setup"); const invite = query.get("invite"); const reset = query.get("reset");
  const mode = setup ? "setup" : invite ? "invite" : reset ? "reset" : "login"; const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [forgot, setForgot] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setPending(true); setError(""); setMessage(""); try {
    if (forgot) { await authApi.forgot(email); setMessage("If that account exists and SMTP is configured, a reset link has been sent."); }
    else if (mode === "login") { const result = await authApi.login(email, password); setCsrfToken(result.csrfToken); signedIn(); }
    else { if (password !== confirm) throw new Error("Passwords do not match."); if (mode === "setup") { const result = await authApi.setup(setup!, email, password); setCsrfToken(result.csrfToken); signedIn(); } else if (mode === "invite") { await authApi.acceptInvite(invite!, password); window.history.replaceState(null, "", "/"); setMessage("Account created. You can now sign in."); window.location.reload(); } else { await authApi.reset(reset!, password); window.history.replaceState(null, "", "/"); setMessage("Password changed. You can now sign in."); window.location.reload(); } }
  } catch (reason) { setError(reason instanceof Error ? reason.message : "Request failed."); } finally { setPending(false); } };
  const title = forgot ? "Reset password" : mode === "setup" ? "Create the administrator" : mode === "invite" ? "Accept invitation" : mode === "reset" ? "Choose a new password" : "Sign in";
  return <div className="auth-shell"><form className="auth-card" onSubmit={submit}><LogoMark /><p className="eyebrow">Sightglass</p><h1>{title}</h1>{setupRequired && !setup ? <div className="notice">Setup is waiting for the private one-time URL printed in the container logs.</div> : null}{mode === "setup" || forgot || (mode === "login" && !setupRequired) ? <label>Email<input type="email" required autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label> : null}{!forgot && (!setupRequired || setup) ? <><label>Password<input type="password" required minLength={12} autoComplete={mode === "login" ? "current-password" : "new-password"} value={password} onChange={(event) => setPassword(event.target.value)} /></label>{mode !== "login" ? <label>Confirm password<input type="password" required minLength={12} autoComplete="new-password" value={confirm} onChange={(event) => setConfirm(event.target.value)} /></label> : null}</> : null}{error ? <div className="error">{error}</div> : null}{message ? <div className="notice good">{message}</div> : null}{(!setupRequired || setup || forgot) ? <button className="primary-button" disabled={pending}>{pending ? "Working…" : forgot ? "Send reset link" : mode === "login" ? "Sign in" : "Continue"}</button> : null}{mode === "login" && !setupRequired ? <button className="link-button" type="button" onClick={() => setForgot(!forgot)}>{forgot ? "Back to sign in" : "Forgot password?"}</button> : null}</form></div>;
}

function PasswordChange({ close, required = false }: { close(): void; required?: boolean }) { const [currentPassword, setCurrent] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); return <div className="modal-backdrop"><form className="auth-card" onSubmit={(event) => { event.preventDefault(); void authApi.changePassword(currentPassword, password).then(close).catch((reason: Error) => setError(reason.message)); }}><h2>Change password</h2>{required ? <p>Your temporary password must be replaced before continuing.</p> : null}<label>Current password<input type="password" required value={currentPassword} onChange={(event) => setCurrent(event.target.value)} /></label><label>New password<input type="password" minLength={12} required value={password} onChange={(event) => setPassword(event.target.value)} /></label>{error ? <div className="error">{error}</div> : null}<button className="primary-button">Save password</button></form></div>; }
function LogoMark() { return <svg className="auth-logo" viewBox="0 0 42 42" aria-hidden="true"><path d="M9 3h24v7c0 5-3 7-5 10 2 3 5 5 5 12v7H9v-7c0-7 3-9 5-12-2-3-5-5-5-10V3Z"/><path d="M14 28c3-3 5-3 7-2 3 2 5 2 7-1v8H14v-5Z"/></svg>; }
